services:
  extract:
    build: .
    command: python extract/extract.py
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    volumes:
      - chess_data:/app/data
    deploy:
      resources:
        limits:
          memory: 3G
        reservations: 
          memory: 3G

volumes:
  chess_data:
